name: algo_viz
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  another_flutter_splash_screen: ^1.2.0
  bloc: ^9.0.0

  cupertino_icons: ^1.0.6


  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0

  fpdart: ^1.1.1

  freezed_annotation: ^2.4.4

  get_it: ^8.0.3

  injectable: ^2.5.0

  intl: ^0.20.1

  json_annotation: ^4.9.0

  lottie: ^3.1.0
  pin_code_fields: 8.0.1

  recase: 4.1.0

  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14

  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.5.7

  injectable_generator: ^2.6.2

  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/images/
